// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package PostgresDB

import (
	"database/sql"
)

type CarList struct {
	ID           int32          `json:"id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeleteAt     sql.NullTime   `json:"delete_at"`
	Email        sql.NullString `json:"email"`
	GoodID       []int32        `json:"good_id"`
	GoodPrice    []int32        `json:"good_price"`
	AllimageName sql.NullString `json:"Allimage_name"`
}

type Good struct {
	ID        int32          `json:"id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeleteAt  sql.NullTime   `json:"delete_at"`
	ImageName sql.NullString `json:"image_name"`
	Descript  sql.NullString `json:"descript"`
	Price     sql.NullInt64  `json:"price"`
	Class     sql.NullString `json:"class"`
}

type Order struct {
	ID              int32          `json:"id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	DeleteAt        sql.NullTime   `json:"delete_at"`
	Amount          []int32        `json:"amount"`
	Owner           sql.NullString `json:"owner"`
	CustomerMessage sql.NullString `json:"customer_message"`
	GoodID          []string       `json:"good_id"`
	TotalPrice      sql.NullInt32  `json:"total_price"`
	Message         sql.NullString `json:"message"`
	Status          sql.NullInt32  `json:"status"`
}
