// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package PostgresDB

import (
	"context"
)

type Querier interface {
	GetGoodList(ctx context.Context) ([]Good, error)
	Insertgoods(ctx context.Context, arg InsertgoodsParams) error
}

var _ Querier = (*Queries)(nil)
