// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package PostgresDB

import (
	"context"
)

type Querier interface {
	DeleteGood(ctx context.Context, id int32) error
	GetGoodList(ctx context.Context) ([]Good, error)
	GetGoodListByPage(ctx context.Context, arg GetGoodListByPageParams) ([]Good, error)
	InsertGoods(ctx context.Context, arg InsertGoodsParams) error
	UpdateGood(ctx context.Context, arg UpdateGoodParams) error
}

var _ Querier = (*Queries)(nil)
