version: "3"                     

services:                          
  redis:                           
    image: redis:7.0.5-alpine      
    volumes:                        
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis_container        
    command: redis-server /usr/local/etc/redis/redis.conf 
    command: redis-server --requirepass yourpassword
    environment:                  
      - ENV=develop
      - requirepass
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
        - postgres:/data/postgres
    restart: unless-stopped

