application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  uploadPath: "./upload"
  mode: "debug"
  appId: "go"
  apiBaseRoute: "/api/v1"
  db:
    DATEBASE_HOST: HOST
    DATEBASE_PORT: PORT
    DATEBASE_USER: USER
    DATEBASE_NAME: NAME
    DATEBASE_PASSWD:  PASSWD