application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  uploadPath: "./upload"
  mode: "debug"
  appId: "go"
  apiBaseRoute: "/api/v1"
  db:
    HOST: 192.168.2.32
    PORT: 5432
    USER: postgres
    NAME: postgres
    PASSWD: postgres
  redis:
    HOST: 192.168.2.32
    PORT: 6379
    DEFAULTDB: postgres
    PASSWD: yourpassword
    POOLSIZE: 10
