name: GitHub Actions Demo
on:
  push:
    branches:
      - "main"
      - "feature-**"
  pull_request:
    branches: ["main"]
jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
